/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance.app.src.test.java.inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
