///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package basiclibrary;
//
//import java.util.Arrays;
//
//public class Library {
//    public static void main(String[] args) {
//
//        System.out.println("Rolling Dice Task");
//        int[] rolls = roll(4);
//        printArray(rolls);
//
//        System.out.println("-----");
//
//        System.out.println("Contains Duplicates Task");
//        int[] duplicatesArray = {1, 2, 3, 4, 5, 6, 4};
//        System.out.println(containsDuplicates(duplicatesArray));
//
//        System.out.println("-----");
//
//        System.out.println("Calculating Averages Task");
//        int[] averageArray = {10, 20, 30, 40, 50};
//        System.out.println(calculateAverage(averageArray));
//
//        System.out.println("-----");
//
//        System.out.println("Arrays of Arrays Task");
//        int[][] weeklyMonthTemperatures = {
//                {66, 64, 58, 65, 71, 57, 60},
//                {57, 65, 65, 70, 72, 65, 51},
//                {55, 54, 60, 53, 59, 57, 61},
//                {65, 56, 55, 52, 55, 62, 57}
//        };
//        int[] lowestAverageArray = calculateLowestAverage(weeklyMonthTemperatures);
//        printArray(lowestAverageArray);
//    }
//
//    public static int[] roll(int n) {
//        int[] rolls = new int[n];
//        for (int i = 0; i < n; i++) {
//            rolls[i] = (int) (Math.random() * 6) + 1; // Simulate a dice roll between 1 and 6
//        }
//        return rolls;
//    }
//
//    public static boolean containsDuplicates(int[] array) {
//        Arrays.sort(array);
//        for (int i = 0; i < array.length - 1; i++) {
//            if (array[i] == array[i + 1]) {
//                return true; // Found a duplicate
//            }
//        }
//        return false; // No duplicates found
//    }
//
//    public static double calculateAverage(int[] array) {
//        double sum = 0;
//        for (int num : array) {
//            sum += num;
//        }
//        return sum / array.length;
//    }
//
//    public static int[] calculateLowestAverage(int[][] arrays) {
//        double lowestAverage = Double.MAX_VALUE;
//        int lowestIndex = -1;
//
//        for (int i = 0; i < arrays.length; i++) {
//            double average = calculateAverage(arrays[i]);
//            if (average < lowestAverage) {
//                lowestAverage = average;
//                lowestIndex = i;
//            }
//        }
//
//        return arrays[lowestIndex];
//    }
//
//    public static void printArray(int[] array) {
//        for (int num : array) {
//            System.out.print(num + " ");
//        }
//        System.out.println();
//    }
//
//}

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;

public class Library {
    public static int[] roll(int n) {
        int[] rolls = new int[n];
        for (int i = 0; i < n; i++) {
            rolls[i] = (int) (Math.random() * 6) + 1; // Simulate a dice roll between 1 and 6
        }
        return rolls;
    }

    public static boolean containsDuplicates(int[] array) {
        Arrays.sort(array);
        for (int i = 0; i < array.length - 1; i++) {
            if (array[i] == array[i + 1]) {
                return true; // Found a duplicate
            }
        }
        return false; // No duplicates found
    }

    public static double calculateAverage(int[] array) {
        double sum = 0;
        for (int num : array) {
            sum += num;
        }
        return sum / array.length;
    }

    public static int[] calculateLowestAverage(int[][] arrays) {
        double lowestAverage = Double.MAX_VALUE;
        int lowestIndex = -1;

        for (int i = 0; i < arrays.length; i++) {
            double average = calculateAverage(arrays[i]);
            if (average < lowestAverage) {
                lowestAverage = average;
                lowestIndex = i;
            }
        }

        return arrays[lowestIndex];
    }
}

